### ISSUE TITLE
[Feature] Landing Page - Calendar

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#11]
**Summary**
Create calendar tab on the portal. This should display the list of all events that are happening during the current month. 

**Task List**
 - [ ] Create calendar view
 - [ ] Navbar calendar icon should be highlighted if the user is on this tab
 - [ ] Calendar should **only** display the current month
 - [ ] Make a GET api call to `/api/event` to fetch all events happening during that month
 - [ ] Display the name & time of the event on the calendar
 - [ ] If user selects an event then create popup / side view with more detailed information about the event (@VidhiJMehta help with mockup for this)

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=412%3A756)

![image](https://user-images.githubusercontent.com/42700872/150661716-b549b234-f26a-4adb-94ff-8f1269c50325.png
