### ISSUE TITLE
[Feature] Landing Page - Profile

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#12]
**Summary**
Create profile tab on the landing page. Allow user to view their current profile & make edits.

**Task List**
 - [ ] Display user's data
 - [ ] Highlight the profile icon in the navbar if user is on this tab
 - [ ] Display the following fields (and do not allow them to be modified) --> `email`, `profile pic`, `account creation date`, and `id`. 
 - [ ] Display tooltip next to `id` saying that "please provide this information to AIS officers if having an issue with your account". Note: This `id` field refers to the user's `UserId` (issued by cognito) which is the partition key for the `User` table in dynamodb.
 - [ ] Display the following fields (and allow them to be modified) --> `netid`, `full name`, `phone?`, @spenpal2000 would appreciate clarification on the exact fields/metadata properties that you'd like to collect from members. These will be shown as editable fields as represented in the mockup
 - [ ] No options to delete user's account / linked accounts. Display message saying "if you'd like to delete your account please email AIS officers / ask in discord and provide your `id`.)

@VidhiJMehta would appreciate help with a slightly modified mockup based on above constraints.

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=412%3A774)

![image](https://user-images.githubusercontent.com/42700872/150661890-8eee8f02-5605-41ce-93b3-ad50fe395b9a.png)

**Comment by spenpal2000** [comment]
Main Editable Things For Profile Page:
- Name
- NetID
- Major
- Phone Number
- Year
- Status: [Active, Probation, Terminated]
  - All members are defaulted to active when they join. If members don't hit the attendance quota by a given date (_let's say May 1st, for example_), then their status is on probation. We individually email the member informing them of their status and give them a chance to appeal. If they don't appeal or their appeal is rejected, then their status is terminated and they are no longer a member

Users should be able to upload/re-upload their resume to the profile page

Event History of a Member should be displayed here, if it is not displayed on the landing page
-

**Comment by harshasrikara** [comment]
> Event History of a Member should be displayed here, if it is not displayed on the landing page

It'll be on the tab called attendance in the navbar
