### ISSUE TITLE
[Feature] Landing Page - Attendance

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#13]
**Summary**
Show user their attendance information for events

**Task List**
 - [ ] Create view for attendance
 - [ ] Highlight attendance icon in navbar if user is on the attendance tab
 - [ ] Provide link to membership requirements at top of page (@spenpal2000 attach link here)
 - [ ] Show total number of events attended (as shown in mockup as 1/3, 2/3, etc)
 - [ ] Display message "membership requirements met ✅" if user has attended 3+ events
 - [ ] Display rolling list of names of events that the user has attended at the bottom

@VidhiJMehta would appreciate slightly modified mockup based on above constraints (only can display name of events attended)

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=412%3A791)

![image](https://user-images.githubusercontent.com/42700872/150662006-8415cea3-fed1-4c92-8fa3-13f71813aab4.png)

**Comment by spenpal2000** [comment]
(Link to Membership Attendance Requirements)[https://docs.google.com/document/d/1nHS3CIcXueuZG8hyNEQH4hkFkdmpL9WY2Q_RfiOXBO4/edit#heading=h.5nfr5vrrbpll]
