### ISSUE TITLE
[Feature] Landing Page - Applications

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#14]
**Summary**
Show applications tab. Note: Hide this tab until backend support is added to display this information.

**Task List**
 - [ ] Create view for applications tab
 - [ ] Highlight application tab in navbar if the user is on this page
 - [ ] Display cards with the following fields `heading`, `description`, `link`.

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=417%3A1538)

![image](https://user-images.githubusercontent.com/42700872/150662188-55b2c441-94f5-45de-a210-a0cdff3c58d8.png)
