### ISSUE TITLE
[Feature] Sign In Page UI

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#8]
**Summary**
Create UI for the Sign In Page

**Task List**
 - [ ] Create view for sign in page
 - [ ] Override the cognito ui for sign in (this needs to be done on the AWS console)
 - [ ] Update sign in to only include sign in with google (this needs to be done on the AWS console)
 - [ ] If user arrives on the landing page & they are unauthenticated redirect them to the sign in page (meaning that the sign in page is the first page that any user should see)

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=456%3A1617)

![image](https://user-images.githubusercontent.com/42700872/150661272-86467ccd-a964-4448-ace6-139d6d352ec8.png)
