### ISSUE TITLE
[Feature] Landing Page

### ISSUE THREAD

**Issue by harshasrikara** [aisutd/membership-portal#9]
**Summary**
Create landing page for the portal (if user is authenticated). This should be at the root of the portal.

**Task List**
 - [ ] Render welcome screen
 - [ ] Render vertical navbar 
 - [ ] Populate navbar with profile icon and message saying "signed in as insert-email" (can access using `session.user.image` and `session.user.email`)
 - [ ] @spenpal2000 suggest additional information to render on this page, see figma attachment below for blank mockup

**Additional context**
[Figma Link](https://www.figma.com/file/o4fuLumcTPJEgy4Elvgkau/AIS-Branding-Brainstorming?node-id=402%3A716)

![image](https://user-images.githubusercontent.com/42700872/150661369-bdebc99c-c42d-4454-892b-0652fa75d64c.png)

**Comment by spenpal2000** [comment]
Here are a couple of ideas to implement for the landing page:

- Upcoming Events (1 week time scope)
- Link to (AIS Membership Plan)[https://aisutd.org/member/info] document, in case they need a refresher on what the plan is about (*can be in the form of a button*)
- Link to buy AIS merch (*can be in the form of a button*)
- Contact Information for AIS

There are some other stuff to add like a job post board (for companies that we are in relation with and are looking to actively recruit), but we don't have resources/connections setup for those kind of things for members yet, so I'd say we put a wait on building those features

**Comment by harshasrikara** [comment]
Zubair, based on the above suggestions I think the simplest thing to display on the homepage is to not display the navbar but rather take up the whole screen with buttons that link to each of those tabs / pages. That way the whole page is just a grid of buttons.
